// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * h​e​l​l​o
	 */
	test: string
	format: {
		/**
		 * {​{​N​u​m​b​e​r​|​n​u​m​b​e​r​}​}
		 */
		number: string
		/**
		 * {​{​N​u​m​b​e​r​|​c​u​r​r​e​n​c​y​}​}
		 */
		currency: string
	}
}

export type TranslationFunctions = {
	/**
	 * hello
	 */
	test: () => LocalizedString
	format: {
		/**
		 * {{Number|number}}
		 */
		number: (arg0: number | string | boolean) => LocalizedString
		/**
		 * {{Number|currency}}
		 */
		currency: (arg0: number | string | boolean) => LocalizedString
	}
}

export type Formatters = {}
