// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	format: {
		/**
		 * {​0​|​N​u​m​b​e​r​}​}
		 * @param {number} 0
		 */
		number: RequiredParams<'0|Number'>
		/**
		 * {​0​|​C​u​r​r​e​n​c​y​}​}
		 * @param {number} 0
		 */
		currency: RequiredParams<'0|Currency'>
	}
}

export type TranslationFunctions = {
	format: {
		/**
		 * {0|Number}}
		 */
		number: (arg0: number) => LocalizedString
		/**
		 * {0|Currency}}
		 */
		currency: (arg0: number) => LocalizedString
	}
}

export type Formatters = {
	Currency: (value: number) => unknown
	Number: (value: number) => unknown
}
